import { NextRequest, NextResponse } from "next/server";
import { client } from "@gradio/client";

export async function POST(req: NextRequest) {
  try {
    const formData = await req.formData();
    const image = formData.get("image") as File;

    if (!image) {
      return NextResponse.json({ error: "No image file provided" }, { status: 400 });
    }

    const flaskUrl = process.env.NEXT_PUBLIC_FLASK_API_URL || "http://localhost:5000";
    
    // Check if we are running in local offline development
    const isLocal = flaskUrl.includes("localhost") || flaskUrl.includes("127.0.0.1") || flaskUrl.includes("192.168.");
    
    if (isLocal) {
      console.log("Running locally. Fetching directly from local Flask backend:", `${flaskUrl}/predict-gradcam`);
      const backendFormData = new FormData();
      backendFormData.append("image", image);

      const response = await fetch(`${flaskUrl}/predict-gradcam`, {
        method: "POST",
        body: backendFormData,
      });

      if (!response.ok) {
        const errorText = await response.text();
        return NextResponse.json(
          { error: `Flask backend error: ${errorText}` },
          { status: response.status }
        );
      }

      const data = await response.json();
      return NextResponse.json(data);
    }

    // In production, connect directly to Hugging Face Space using the official Gradio JS Client
    let spaceUrl = flaskUrl;
    if (spaceUrl.includes("/flask-api")) {
      spaceUrl = spaceUrl.replace("/flask-api", "");
    }
    if (spaceUrl.includes("/api")) {
      spaceUrl = spaceUrl.replace("/api", "");
    }

    console.log("Connecting to Gradio client for Hugging Face Space:", spaceUrl);

    // Connect to Gradio Space
    const app = await client(spaceUrl, {
      token: (process.env.HF_ACCESS_TOKEN as `hf_${string}`) || undefined,
    });

    console.log("Sending prediction request to Gradio endpoint /predict_tbc...");
    
    // Call the named predict_tbc endpoint
    const result = await app.predict("/predict_tbc", [image]);

    const dataArray = result.data as any;
    if (!result || !dataArray || !Array.isArray(dataArray) || dataArray.length < 3) {
      throw new Error("Invalid response schema received from Gradio API");
    }

    // 1. Parse text diagnosis results
    const text = dataArray[0] as string;
    const label = text.includes("Diagnosis: Tuberculosis") ? "Tuberculosis" : "Normal";
    
    const confidenceMatch = text.match(/Confidence:\s*([\d\.]+)%/);
    const probMatch = text.match(/probability:\s*([\d\.]+)/);
    const confidence = confidenceMatch ? parseFloat(confidenceMatch[1]) : 0.0;
    const raw_probability = probMatch ? parseFloat(probMatch[1]) : 0.0;

    // Helper to download the temp file generated by Gradio and convert it to Base64
    const convertGradioFileToBase64 = async (fileObj: any) => {
      if (!fileObj || !fileObj.url) return undefined;
      console.log("Downloading result file from Gradio:", fileObj.url);
      const res = await fetch(fileObj.url);
      if (!res.ok) {
        throw new Error(`Failed to download file from Gradio: ${res.statusText}`);
      }
      const arrayBuffer = await res.arrayBuffer();
      const buffer = Buffer.from(arrayBuffer);
      return `data:${fileObj.mime_type || "image/png"};base64,${buffer.toString("base64")}`;
    };

    // 2. Fetch and convert result images to base64 to match PredictionResult structure
    const heatmap_image = await convertGradioFileToBase64(dataArray[1]);
    const superimposed_image = await convertGradioFileToBase64(dataArray[2]);

    console.log("Gradio proxy analysis completed successfully!");

    return NextResponse.json({
      label,
      confidence,
      raw_probability,
      heatmap_image,
      superimposed_image
    });

  } catch (error: any) {
    console.error("Gradio proxy exception:", error);
    return NextResponse.json(
      { error: error.message || "Failed to process prediction via Hugging Face Space client" },
      { status: 500 }
    );
  }
}
